name: update firestore from functions api

on:
  workflow_dispatch:

jobs:
  run-ts-and-call-api:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # OIDC トークン発行を許可
      contents: read

    steps:
      # リポジトリのコードを取得
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js の設定
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 必要なパッケージのインストール
      - name: Install dependencies
        run: npm install

      - name: Generate OIDC Token
        id: get-jwt
        run: |
          echo "Requesting OIDC Token..."
          TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            -H "Accept: application/json" \
            https://token.actions.githubusercontent.com/token?audience=https://firestore-fzxwlwc6iq-an.a.run.app/forecast)

          # OIDC token header, payload test
          curl -s -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" "${ACTIONS_ID_TOKEN_REQUEST_URL}" | jq '.value | split(".") | .[0],.[1] | @base64d | fromjson'

          # トークンの取得結果を表示
          echo "Raw Token Response: $TOKEN"

          # トークンを抽出
          JWT_TOKEN=$(echo $TOKEN | jq -r '.value')

          # JWT_TOKENの内容を表示
          echo "Extracted JWT Token: $JWT_TOKEN"

          # 環境変数に設定
          echo "JWT_TOKEN=$JWT_TOKEN" >> $GITHUB_ENV

      # TypeScript ファイルを実行して外部APIを叩き、Firestore APIに送信
      - name: Run TypeScript File
        run: |
          # TypeScript コンパイル
          npx tsc

          # 実行
          node dist/for-github-actions/fetchData.js
        env:
          JWT_TOKEN: ${{ env.JWT_TOKEN }}
