name: update firestore from functions api

on:
  workflow_dispatch:

jobs:
  run-ts-and-call-api:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # OIDC トークン発行を許可
      contents: read

    steps:
      # リポジトリのコードを取得
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js の設定
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ^18

      # 必要なパッケージのインストール
      - name: Install dependencies
        run: npm install

      # Actions 環境変数の読み込み: 毎回これが必要
      - name: Load environment variables
        run: |
          echo "FUNCTIONS_URL=${{ vars.FUNCTIONS_URL }}" >> $GITHUB_ENV

      # TODO: 今はテストでforecastのみにしている。他のAPIエンドポイントも後から追加する
      - name: Generate OIDC Token
        id: get-jwt
        run: |
          echo "Requesting OIDC Token..."
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
          jwt_token=$(curl -v -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            -H "Accept: application/json" \
            "https://token.actions.githubusercontent.com/?audience=https://accounts.google.com")
          echo "JWT Token Response: $jwt_token"


          echo "JWT_TOKEN=$jwt_token" >> $GITHUB_ENV

      - name: Check JWT Token
        run: |
          echo "Decoding JWT Token..."
          echo ${{ env.JWT_TOKEN }} | base64 -d

      # TypeScript ファイルを実行して外部APIを叩き、Functions APIに送信
      - name: Run TypeScript File
        run: |
          npx tsc
          node dist/for-github-actions/fetchData.js
        env:
          JWT_TOKEN: ${{ env.JWT_TOKEN }}
