name: save to firestore from functions api

on:
  workflow_dispatch:

jobs:
  run-ts-and-call-api:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # OIDC トークン発行を許可
      contents: read

    steps:
      # リポジトリのコードを取得
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js の設定
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 必要なパッケージのインストール
      - name: Install dependencies
        run: npm install

      # JWTトークンを取得
      - name: Generate OIDC Token
        id: get-jwt
        run: |
          echo "JWT_TOKEN=$(curl -s -H 'Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN' \
            -H 'Accept: application/json' \
            https://vstoken.actions.githubusercontent.com/v1/token?audience=https://firestore-fzxwlwc6iq-an.a.run.app/forecast)" \
            >> $GITHUB_ENV

      # TypeScript ファイルを実行して外部APIを叩き、Firestore APIに送信
      - name: Run TypeScript File
        run: |
          # TypeScript コンパイル
          npx tsc

          # 実行
          node dist/for-github-actions/fetchData.js
        env:
          JWT_TOKEN: ${{ env.JWT_TOKEN }}
