name: update firestore from functions api

on:
  workflow_dispatch:

jobs:
  run-ts-and-call-api:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # OIDC トークン発行を許可
      contents: read

    steps:
      # リポジトリのコードを取得
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js の設定
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ^18

      # 必要なパッケージのインストール
      - name: Install dependencies
        run: npm install

      - name: Show env
        run: env | grep 'ACTIONS_ID_TOKEN'

      - name: OIDC test
        run: |
          curl --silent \
            -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}" | jq -r '.value'

      - name: Request OIDC token
        run: |
          # oidcTokenにOIDCトークンを設定
          oidcToken=$(curl --silent \
            -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}" | jq -r '.value')

          echo "OIDC Token Payload:"
          echo "$oidcToken" | base64 -d | jq

          echo "JWT_TOKEN=$oidcToken" >> $GITHUB_ENV

      - name: Run TypeScript
        run: |
          npx tsc
          node dist/for-github-actions/fetchData.js
        # ファイル内で使う環境変数を設定
        env:
          FUNCTIONS_URL: ${{ vars.FUNCTIONS_URL }}
